config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :projects
  map.resources :groups

  

  map.root :controller => "projects"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_projects, :dependent => :destroy
  has_many :projects, :through => :group_projects
  
  def self.all_active
    Group.find(:all, :conditions => ["start_date >= ? AND end_date <= ?", Time.now.beginning_of_week, Time.now.end_of_week])
  end
  
end

app/models/group_project.rb
class GroupProject < ActiveRecord::Base
  belongs_to :group
  belongs_to :project
end

app/models/harvest.rb
SUBDOMAIN        = SUBDOMAIN       
ACCOUNT_EMAIL    = ACCOUNT_EMAIL   
ACCOUNT_PASSWORD = ACCOUNT_PASSWORD
USER_AGENT       = 'HarvestTarget'
HAS_SSL          = true


# everything is in utf8
$KCODE = 'u'

require 'base64'
require 'bigdecimal'
require 'date'
require 'jcode'
require 'net/http'
require 'net/https'
require 'time'

class Harvest

  def initialize
    @company             = SUBDOMAIN
    @preferred_protocols = [HAS_SSL, ! HAS_SSL]
    connect!
  end

  # HTTP headers you need to send with every request.
  def headers
    {
      # Declare that you expect response in XML after a _successful_
      # response.
      "Accept"        => "application/xml",

      # Promise to send XML.
      "Content-Type"  => "application/xml; charset=utf-8",

      # All requests will be authenticated using HTTP Basic Auth, as
      # described in rfc2617. Your library probably has support for
      # basic_auth built in, I've passed the Authorization header
      # explicitly here only to show what happens at HTTP level.
      "Authorization" => "Basic #{auth_string}",

      # Tell Harvest a bit about your application.
      "User-Agent"    => USER_AGENT
    }
  end

  def auth_string
    Base64.encode64("#{ACCOUNT_EMAIL}:#{ACCOUNT_PASSWORD}").delete("\r\n")
  end

  def request path, method = :get, body = ""
    response = send_request( path, method, body)
    if response.class < Net::HTTPSuccess
      # response in the 2xx range
      on_completed_request
      return response
    elsif response.class == Net::HTTPServiceUnavailable
      # response status is 503, you have reached the API throttle
      # limit. Harvest will send the "Retry-After" header to indicate
      # the number of seconds your boot needs to be silent.
      raise "Got HTTP 503 three times in a row" if retry_counter > 3
      sleep(response['Retry-After'].to_i + 5)
      request(path, method, body)
    elsif response.class == Net::HTTPFound
      # response was a redirect, most likely due to protocol
      # mismatch. Retry again with a different protocol.
      @preferred_protocols.shift
      raise "Failed connection using http or https" if @preferred_protocols.empty?
      connect!
      request(path, method, body)
    else
      dump_headers = response.to_hash.map { |h,v| [h.upcase,v].join(': ') }.join("\n")
      raise "#{response.message} (#{response.code})\n\n#{dump_headers}\n\n#{response.body}\n"
    end
  end

  private

  def connect!
    port = has_ssl ? 443 : 80
    @connection             = Net::HTTP.new("#{@company}.harvestapp.com", port)
    @connection.use_ssl     = has_ssl
    @connection.verify_mode = OpenSSL::SSL::VERIFY_NONE if has_ssl
  end

  def has_ssl
    @preferred_protocols.first
  end

  def send_request path, method = :get, body = ''
    case method
    when :get
      @connection.get(path, headers)
    when :post
      @connection.post(path, body, headers)
    when :put
      @connection.put(path, body, headers)
    when :delete
      @connection.delete(path, headers)
    end
  end

  def on_completed_request
    @retry_counter = 0
  end

  def retry_counter
    @retry_counter ||= 0
    @retry_counter += 1
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :time_entries, :foreign_key => :harvest_user_id, :primary_key => :harvest_user_id
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :time_entries, :foreign_key => :harvest_project_id, :primary_key => :harvest_id
  has_many :people, :through => :time_entries
  has_many :group_projects, :dependent => :destroy
  has_many :groups, :through => :group_projects
end

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
  belongs_to :person, :foreign_key => :harvest_user_id, :primary_key => :harvest_user_id
  
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
  def open_harvest_connection
    @harvest = Harvest.new
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @projects = Project.find(:all, :conditions => ["updated_at >= ?", Time.now.beginning_of_week])
    @group = Group.new
  end
  
  def create
    @group = Group.create(params[:group])
    redirect_to group_path(@group)
  end
  
  def edit
    @group = Group.find(params[:id])
    @projects = Project.find(:all, :conditions => ["updated_at >= ?", Time.now.beginning_of_week])
  end

  def update
    @group = Group.find(params[:id])
    @group.update_attributes(params[:group])
    redirect_to group_path(@group)
  end
  
  def show
    @group = Group.find(params[:id])
    @projects = @group.projects.all
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :open_harvest_connection

  def index
    @projects = Project.find(:all, :conditions => ["updated_at >= ?", Time.now.beginning_of_week])
  end
  
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
  
  def get_color_code(i)
    case i
    when 0
      '#0000ff'
    when 1
      '#0099ff'
    when 2
      '#0ff'
    when 3
      '#c00'
    when 4
      '#99cc00'
    when 5
      '#ff0'
    when 6
      'DarkMagenta'
    when 7
      'DarkSlateGray'
    when 8
      'Blue'
    when 9
      'Gold'
    when 10
      'Gray'
    when 11
      'Black'
    end
  end
  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/groups/_form.erb
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :start_date %>
  <%= f.datetime_select :start_date, :default => Time.now.beginning_of_week %>
</p>
<p>
  <%= f.label :end_date %>
  <%= f.datetime_select :end_date, :default => Time.now.end_of_week %>
</p>
<% @projects.each do |project| %>
  <p><%= check_box_tag 'group[project_ids][]', "#{project.id}", @group.projects.include?(project) ? true : false %> <%= project.name %></p>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing <%= @group.name %></h1>
<br/>
<% form_for @group do |f| %>
  <%= render :partial => "form", :locals => {:f  => f} %>
  <%= f.submit "Update Group" %>
    
<% end %>

app/views/groups/new.html.erb
<h1>Create a group of projects</h1>
<br/>
<% form_for @group do |f| %>
  <%= render :partial => "form", :locals => {:f  => f} %>
  <%= f.submit "Create Group" %>
    
<% end %>

app/views/groups/show.html.erb
<h1><%= @group.name %><%= link_to "edit", edit_group_path(), :class => "action-link" %></h1>
<hr/>
<% @projects.each do |project| %>
  <h1><%= project.name %> : <%= project.time_entries.map{|te| te.hours if te.date >= Time.now.beginning_of_week }.compact.sum %></h1>
  <div class="progress-bar-container">
    <% project.time_entries.map{|te| te.person}.uniq.each_with_index do |person, i| %>
      <% entries = project.time_entries.select{|te| te.date >= Time.now.beginning_of_week && te.person == person} %>
      <% user_hours = entries.map{|e| e.hours if e.date >= Time.now.beginning_of_week && e.date <= Time.now.end_of_week}.compact.sum %>
      <% if user_hours > 0 %>
        <div style="width:<%= ((user_hours)/35*100).to_i %>%;background:<%= get_color_code(i) %>;" class="progress-bar"> <%= person.first_name %> <%= person.last_name %> <%= user_hours %></div>
      <% end %>
    <% end %>
    <br style="clear:both;" />

  </div>
  <% project.time_entries.map{|te| te.person}.uniq.each_with_index do |person, i| %>
    <% entries = project.time_entries.select{|te| te.person == person} %>
    <%= person.first_name %> <%= person.last_name %> <%= entries.map{|e| e.hours if e.date >= Time.now.beginning_of_week && e.date <= Time.now.end_of_week}.compact.sum %><br/>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <%= stylesheet_link_tag("reset","application")  %>
    <link media="only screen and (max-device-width: 480px)" 
        href="/stylesheets/iphone.css" type="text/css" rel="stylesheet" />
    
  </head>
  <body>
    <div class="nav-bar">
      <div class="nav-bar-restraint">
        <%= link_to "All Projects", projects_path %> | <%= link_to "Create Group", new_group_path() %>
        <% Group.all_active.each do |group| %>
          | <%= link_to group.name, group_path(group.id) %>
        <% end %>
        
      </div>
    </div>
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
  <h1><%= project.name %></h1>
  <div class="progress-bar-container">
    <% project.time_entries.map{|te| te.person}.uniq.each_with_index do |person, i| %>
      <% entries = project.time_entries.select{|te| te.person == person} %>
      <div style="width:<%= ((entries.map{|e| e.hours if e.date >= Time.now.beginning_of_week && e.date <= Time.now.end_of_week}.compact.sum)/35*100).to_i %>%;background:<%= get_color_code(i) %>;" class="progress-bar"> <%= person.first_name %> <%= person.last_name %> <%= entries.map{|e| e.hours if e.date >= Time.now.beginning_of_week && e.date <= Time.now.end_of_week}.compact.sum %></div>
    <% end %>
    <br style="clear:both;" />
  </div>
<% end %>